function updateOverlay(pos, hFace, face_img, mask)
% for live overlay
set(hFace,'XData',[pos(1), pos(1)+pos(3)], ...
              'YData',[pos(2), pos(2)+pos(4)], ...
              'CData', imresize(face_img,[pos(4), pos(3)]), ...
              'AlphaData', imresize(mask,[pos(4), pos(3)]));
end%EOF